Make recommended videos only come from the channel the video belongs to
gamejolt/gamejolt pull request #613
Opened 2020-08-18 10:08 UTC by YLivay

A reasonable request detailed [here](https://gamejolt.com/@CHILL_NPLAY/post/why-do-my-videos-have-the-notification-watch-other-videos-here-al-be8ctkmd).

https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018

2020-08-20 06:26 UTC, nilllzz approved these changes

2020-09-10 19:09 UTC, hworld approved these changes

2020-09-10 19:11 UTC, hworld requested changes

2020-09-10 19:11 UTC, hworld commented on src/_common/video/embed/embed.ts
> +			queryParams.push('rel=0');
actually, I changed my mind. put a comment above this with the link to information of what it does.

2020-09-30 15:50 UTC, nilllzz approved these changes

2020-10-16 15:00 UTC, merged