Allow shorthand links for embedding youtube videos
gamejolt/gamejolt pull request #616
Opened 2020-08-26 22:14 UTC by hapurubokka

fixes https://github.com/gamejolt/issue-tracker/issues/1347

2020-08-27 15:51 UTC, hworld commented on src/_common/content/content-editor/embeds/youtube-video.ts
> +		if (results && results.length === 11) {
we shouldn't check the length, it might change in future

2020-08-27 15:52 UTC, hworld commented on src/_common/content/content-editor/embeds/youtube-video.ts
> +		if (results && results.length === 11) {
Also, isValidLink should probably just return a boolean.
You can call getYoutubeVideoId above in the getLinkSource directly

2020-08-27 15:53 UTC, hworld commented on src/app/components/forms/game/video/video.ts
> +			const youtubeMatch = url.match(REGEX_YOUTUBE);
I feel like we can put that getYoutubeVideoId function somewhere in util folder and then change this code to use a generic function that would get the video match with the "provider". What do you think?

2020-09-03 18:20 UTC, hworld requested changes

2020-09-03 18:20 UTC, hworld commented on src/_common/game/video/video.model.ts
> +	readonly REGEX = {
are these used?

2020-09-03 18:20 UTC, hworld commented on src/_common/content/content-editor/embeds/youtube-video.ts
> +		const results = REGEX_YOUTUBE.exec(link);
just  `return REGEX_YOUTUBE.test(link);`

2020-09-03 21:53 UTC, hapurubokka commented on src/_common/game/video/video.model.ts
> +	readonly REGEX = {
I can't find them being used anymore - removed.

2020-09-04 01:13 UTC, hworld approved these changes

2020-09-04 18:39 UTC, merged