Fix account-popover active indicator
gamejolt/gamejolt pull request #625
Opened 2020-08-29 20:28 UTC by hapurubokka

2020-09-01 18:27 UTC, nilllzz requested changes

2020-09-01 18:27 UTC, nilllzz commented on src/app/components/shell/account-popover/account-popover.vue
>  			<div
I am not 100% sure, but I don't think you can self-close div tags in HTML5.

2020-09-01 18:27 UTC, nilllzz commented on src/app/components/shell/account-popover/account-popover.vue
> -						<span v-if="shouldShowNewStickers" class="-new-tag -new-tag-list"></span>
Also can't self-close spans.
Reference: https://html.spec.whatwg.org/multipage/syntax.html#start-tags (specifically 6.)
Valid self-closing elements are the "void elements" in this specification: https://html.spec.whatwg.org/multipage/syntax.html#void-elements

2020-09-03 18:15 UTC, hworld approved these changes

2020-09-04 18:40 UTC, merged