Add a user-status bubble to the chat window
gamejolt/gamejolt pull request #630
Opened 2020-09-01 15:06 UTC by hapurubokka

allows you to see if the person you're messaging is online for breakpoints that use a full-screen chat window

2020-09-01 18:20 UTC, nilllzz approved these changes

2020-09-03 18:25 UTC, hworld requested changes

2020-09-03 18:25 UTC, hworld commented on src/app/components/chat/window/window.styl
> +		.-user-status
Maybe we can make a user-online-status component instead

2020-09-04 01:11 UTC, hworld approved these changes

2020-09-04 18:39 UTC, merged